### ISSUE TITLE
English readme? 

### ISSUE THREAD

**Issue by albertyou2** [eastxe/picture-clustering#2]
@eastxe hi,could you please give a simple english readme for showing us how to use this repo?
Thank you very much

**Comment by eastxe** [comment]
OK. I wrote an English document.
To use this repository, you need Caffe and a model definition file.

*note*

This repo classifies multiple images by unsupervised learning with Caffe.
Please note that it is different from supervised learning generally used in clustering.
If you want to do the intended clustering, try another way in supervised learning.

**Comment by eastxe** [comment]
OK. I wrote an English document.
Caffe and Imagenet model files are required to use this repository.

*note*

After obtaining the feature vector by Caffe,
this example classifies multiple images by unsupervised learning.
Please note that it is different from supervised learning generally used in classification.
If you want to do the intended clustering, try another way in supervised learning.

**Comment by albertyou2** [comment]
HI @eastxe ,Thank you for helping!
unsupervised learning for image clustering is what I'm looking for.
And extracting features by CNN and then clustering is a perfect method for my problem .
Because I think CNN could learn high level features from images.

I will follow your instructions and have a try !Thank you again.

**Comment by albertyou2** [comment]
hi @eastxe 
Sorry for trouble you again.

I 'm new with caffe .So I can't find the model files as you said.

1. **meanfile: ilsvrc_2012_mean.npy**  ---> I find it in my caffe path. 

2. **modelfile: caffe_reference_imagenet_model** ---> I can't find it in my caffe ,and  then I tried to download it .But I found that there are many models in caffe model zoo: https://github.com/BVLC/caffe/wiki/Model-Zoo.
which one should download?

3. **networkfile: imagenet_deploy.prototxt**. ---> I also can't find it in my caffe path . But I found a deploy.prototxt in : 
/caffe/models/bvlc_reference_caffenet/deploy.prototxt . Do you mean this file?

Thank you!

**Comment by eastxe** [comment]
I'm sorry, I forgot to write about that.
README.md has been updated.
I think this is the easiest way.
Please see there for details.
Also I wrote about updating imagenet_feature.prototxt.

clustering_example.py has also been modified slightly.
Hope this helps.

**Comment by eastxe** [comment]
Sorry, I forgot to write about that.
README.md has been updated.
I think this is the easiest way.
Please see it for details.
Also I wrote about updating imagenet_feature.prototxt.

clustering_example.py has also been modified slightly.
Hope this helps.

**Comment by albertyou2** [comment]
HI @eastxe 
Thank you for updating.

I tried that and met a new problem .
The URL in "get_caffe_reference_imagenet_model.sh" is not working.The host "www.dropbox.com" could not be reached.

The error log here: 
--2016-12-05 13:45:12--  https://www.dropbox.com/s/n3jups0gr7uj0dv/caffe_reference_imagenet_mode
Resolving www.dropbox.com... 46.82.174.68, 200:2:4e10:310f::
Connecting to www.dropbox.com|46.82.174.68|:443... failed: Operation timed out.
Connecting to www.dropbox.com|200:2:4e10:310f::|:443... failed: No route to host.

Does this url can only be reached from Japan?

**Comment by albertyou2** [comment]
@eastxe  I think I found the reason.In our country dropbox tools and apis are both prohibited .
I 'am using proxy to download it .
I 'll let you know the result when I had download the model and had a try!

**Comment by albertyou2** [comment]
@eastxe 

when i use feature.py to extract features .I met this error :

I1205 16:46:30.054661 23998 upgrade_proto.cpp:61] Successfully upgraded file specified using deprecated V1LayerParameter
I1205 16:46:30.084415 23998 net.cpp:761] Ignoring source layer data
I1205 16:46:30.120198 23998 net.cpp:761] Ignoring source layer loss
Traceback (most recent call last):
  File "feature.py", line 82, in <module>
    I = Feature(flag_separate=False)
  File "feature.py", line 26, in __init__
    self.net.transformer.set_mean('data', np.load(MEAN))
  File "/home/sojoyoo/caffe/python/caffe/io.py", line 259, in set_mean
    raise ValueError('Mean shape incompatible with input shape.')
ValueError: Mean shape incompatible with input shape.

Should I resize the image's width and height as the same as the image net datase's?

**Comment by eastxe** [comment]
There is no need to resize the image.

Apparently it seems to be a bug in Caffe.
Please refer to the following URL.

http://stackoverflow.com/questions/28692209/using-gpu-despite-setting-cpu-only-yielding-unexpected-keyword-argument

***

It would be nice to do this.

```
caffe/python/caffe/io.py
```
line: 253-254

```
if ms != self.inputs[in_][1:]:
    raise ValueError('Mean shape incompatible with input shape.')
```

Please correct this as follows.

```
if ms != self.inputs[in_][1:]:
    print(self.inputs[in_])
    in_shape = self.inputs[in_][1:]
    m_min, m_max = mean.min(), mean.max()
    normal_mean = (mean - m_min) / (m_max - m_min)
    mean = resize_image(normal_mean.transpose((1,2,0)),in_shape[1:]).transpose((2,0,1)) * (m_max - m_min) + m_min
    #raise ValueError('Mean shape incompatible with input shape.')
```

I think that it will be settled with this.

**Comment by eastxe** [comment]
There is no need to resize the image.

Apparently it seems to be a bug in Caffe.
Please refer to the following URL.

http://stackoverflow.com/questions/28692209/using-gpu-despite-setting-cpu-only-yielding-unexpected-keyword-argument

***

Do it like this.

```
caffe/python/caffe/io.py
```
line: 253-254

```
if ms != self.inputs[in_][1:]:
    raise ValueError('Mean shape incompatible with input shape.')
```

Please correct this as follows.

```
if ms != self.inputs[in_][1:]:
    print(self.inputs[in_])
    in_shape = self.inputs[in_][1:]
    m_min, m_max = mean.min(), mean.max()
    normal_mean = (mean - m_min) / (m_max - m_min)
    mean = resize_image(normal_mean.transpose((1,2,0)),in_shape[1:]).transpose((2,0,1)) * (m_max - m_min) + m_min
    #raise ValueError('Mean shape incompatible with input shape.')
```

I think that it will be settled with this.

**Comment by eastxe** [comment]
There is no need to resize the image.

Apparently it seems to be a bug in Caffe.
Please refer to the following URL.

http://stackoverflow.com/questions/28692209/using-gpu-despite-setting-cpu-only-yielding-unexpected-keyword-argument

***

Do it like this.

```
caffe/python/caffe/io.py
```
line: 253-254
```
if ms != self.inputs[in_][1:]:
    raise ValueError('Mean shape incompatible with input shape.')
```
Please correct this as follows.
```
if ms != self.inputs[in_][1:]:
    print(self.inputs[in_])
    in_shape = self.inputs[in_][1:]
    m_min, m_max = mean.min(), mean.max()
    normal_mean = (mean - m_min) / (m_max - m_min)
    mean = resize_image(normal_mean.transpose((1,2,0)),in_shape[1:]).transpose((2,0,1)) * (m_max - m_min) + m_min
    #raise ValueError('Mean shape incompatible with input shape.')
```
I think that it will be settled with this.

**Comment by albertyou2** [comment]
@eastxe  
it works now !thank you very much !

**Comment by albertyou2** [comment]
@eastxe HI !
Today I had finished a experiment of clustering my images which are downloaded from internet.
The result is very exciting! It is beyond my expectation.The accuracy is about 70%~80%. Really a great work!

Note that the accuracy  of using 'SpectralClustering' is very bad but using the Kmeans's is very good .
So I think you could add kmeans in your code to improve the  Accuracy for others. 

**This is my implemation** :
print('kmeans clustering')
kmeans   = KMeans(n_clusters=2, n_init=10000,max_iter=20000,tol=0.01,precompute_distances=True).fit(data)
k_labels = kmeans.fit_predict(data)
result('kmeans',filenames,k_labels)

**NOTE: I modify your 'result' function**
def result(prefix,filenames,labels):
    n_clusters = max(labels)
    path = './'+prefix+'_result/'
    if os.path.exists(path) == True:
        shutil.rmtree(path)
    for i in xrange(n_clusters + 1):
        if not os.path.exists( path + str(i)):
            os.makedirs(path + str(i))
    for label, txtname in zip(labels, filenames):
        name = txtname[0:txtname.rfind('.')] + '.jpg'
        shutil.copyfile('./data/' + name,path + str(label) + '/' + name)

**NOTE:kmeans is too slow . 177 images(220*220) spend about 1 hour！**

Some discussion here:
1) I read your code and found this line :
'self.INDEX = 4'
what does that mean?

2) have you  tried  using features that  extracted from conv layer( not from the FC layer) ?If you have tried ,what about the result?

3) If the differences between images become smaller,in another word the pictures are becoming more and more similar,but human could still distinguish them .Do you have any suggestion for handle this case?Will switch to a deeper and larger network in feature extraction help this ?

**Comment by eastxe** [comment]
Sorry for my late reply.

Generally, In high-dimensional space, k-means does not work well because of 'the curse of dimensionality' (especially since sklearn implementation is Euclidean distance).
So, I do not recommend k-means much.
However, actually trying it seems that k-means also works well for images that are easy to separate.
If I try this on an image that is difficult to separate, and it works well, I may add k-means among them.
Also, problems with long k-means execution time are improved by reducing the number of iterations.

1.
self.net.blobs[self.LAYER].data is a matrix of (10, 4096).
In this code, the fifth vector of ten is taken as the feature vector.
(Actually, the first to fifth vectors are the same.)

2.
No, I have not tried it.
The reason is that the output of the conv layer is a vector having a visual meaning, and the output of the fc layer is a vector useful for classification.

3.
Please try fine-tuning.

**Comment by albertyou2** [comment]
@eastxe OK!
I 'll do some experiments based on your research !
